openapi: 3.0.0
info:
  description: "ONDC Participant Management API"
  version: 2.0.5
  title: "ONDC Registry "
tags:
- name: "ONDC Network Participant Onboarding"
  description: "Registration, amendment, key rotation"
paths:
  /subscribe:
    post:
      tags:
        - ONDC Network Participant Onboarding
      description: subscriber
      requestBody:
        description: Onboard
        content:
          application/json:
            schema:
              type: object
              properties:
                context:
                  type: object
                  properties:
                    operation:
                      $ref: '#/components/schemas/Context'
                message:
                  type: object
                  properties:
                    request_id:  
                      type: string  
                      description: A unique request id generated by network participant to track each request.
                    timestamp:
                      type: string
                      format: date-time
                      description: Time of request generation in RFC3339 format
                      example: 2022-07-07T02:52:29.001Z
                    entity:
                      $ref: '#/components/schemas/Entity'
                    network_participant:
                      type: array
                      items:
                        $ref: '#/components/schemas/NetworkParticipant'
                  required:
                  - entity
                  - timestamp
                  - network_participant
              required:
                  - context
                  - message
            examples:
                ops_no_1:
                  value:
                    context: 
                      operation:
                        ops_no: 1
                      request_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                      timestamp: 2022-07-08T13:44:54.101Z
                      entity: 
                        gst: 
                          legal_entity_name: ABC Incorporates
                          business_address: Trade World, Mansarpur, Coorg, Karnataka 333333
                          city_code: ["std:080"]
                          gst_no: 07AAACN2082N4Z7
                        pan: 
                          name_as_per_pan: ABC Incorporates
                          pan_no: ASDFP7657Q
                          date_of_incorporation: 23/06/1982
                        name_of_authorised_signatory: Anand Sharma
                        address_of_authorised Signatory: 405, Pinnacle House, Kandiwali, Mumbai 400001
                        email_id: anand.sharma@abc.com
                        mobile_no: 9912332199
                        country: IND
                        subscriber_id: sit.grab.in
                        unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                        callback_url: /ondc/onboarding
                        key_pair: 
                          signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                          encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                          valid_from: 2022-07-08T13:44:54.101Z
                          valid_until: 2022-07-08T13:44:54.101Z
                      network_participant: [
                        {
                        subscriber_url: /bapl,
                        domain: nic2004:52110,
                        type: buyerApp,
                        msn: false,
                        city_code: ["std:080"]
                        }
                      ]
                      
                ops_no_2:
                  value:
                    context: 
                      operation:
                        ops_no: 2
                    message:
                      request_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                      timestamp: 2022-07-08T13:44:54.101Z
                      entity: 
                        gst: 
                          legal_entity_name: ABC Incorporates
                          business_address: Trade World, Mansarpur, Coorg, Karnataka 333333
                          city_code: [std:080]
                          gst_no: 07AAACN2082N4Z7
                        pan: 
                          name_as_per_pan: ABC Incorporates
                          pan_no: ASDFP7657Q
                          date_of_incorporation: 23/06/1982
                        name_of_authorised_signatory: Anand Sharma
                        address_of_authorised Signatory: 405, Pinnacle House, Kandiwali, Mumbai 400001
                        email_id: anand.sharma@abc.com
                        mobile_no: 9912332199
                        country: IND
                        subscriber_id: sit.grab.in
                        unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                        callback_url: /ondc/onboarding
                        key_pair: 
                          signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                          encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                          valid_from: 2022-07-08T13:44:54.101Z    
                          valid_until: 2022-07-08T13:44:54.101Z
                      network_participant: [
                        {
                        subscriber_url: /bapl,
                        domain: nic2004:52110,
                        type: sellerApp,
                        msn: false,
                        city_code: ["std:080"]
                        }
                        ]
                      
                ops_no_3:
                  value:
                    context: 
                      operation:
                        ops_no: 3
                    message:
                      request_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                      timestamp: 2022-07-08T13:44:54.101Z
                      entity: 
                        gst: 
                          legal_entity_name: ABC Incorporates
                          business_address: Trade World, Mansarpur, Coorg, Karnataka 333333
                          city_code: ["std:080"]
                          gst_no: 07AAACN2082N4Z7
                        pan: 
                          name_as_per_pan: ABC Incorporates
                          pan_no: ASDFP7657Q
                          date_of_incorporation: 23/06/1982
                        name_of_authorised_signatory: Anand Sharma
                        address_of_authorised Signatory: 405, Pinnacle House, Kandiwali, Mumbai 400001
                        email_id: anand.sharma@abc.com
                        mobile_no: 9912332199
                        country: IND
                        subscriber_id: sit.grab.in
                        unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                        callback_url: /ondc/onboarding
                        key_pair: 
                          signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                          encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                          valid_from: 2022-07-08T13:44:54.101Z
                          valid_until: 2022-07-08T13:44:54.101Z
                      network_participant: 
                        subscriber_url: /bapl
                        domain: nic2004:52110
                        type: sellerApp
                        msn: true
                        city_code: ["std:080"]
                        seller_on_record: [
                          {
                          unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04,
                          key_pair: 
                          {
                            signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=,
                            encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=,
                            valid_from: 2022-07-08T13:44:54.101Z,
                            valid_until: 2022-07-08T13:44:54.101Z
                          },
                          city_code: ["std:080"] 
                          }
                          ]
                          
                ops_no_4:
                  value:
                    context: 
                      operation:
                        ops_no: 4
                    message:
                      request_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                      timestamp: 2022-07-08T13:44:54.101Z
                      entity: 
                        gst: 
                          legal_entity_name: ABC Incorporates
                          business_address: Trade World, Mansarpur, Coorg, Karnataka 333333
                          city_code: [std:080]
                          gst_no: 07AAACN2082N4Z7
                        pan: 
                          name_as_per_pan: ABC Incorporates
                          pan_no: ASDFP7657Q
                          date_of_incorporation: 23/06/1982
                        name_of_authorised_signatory: Anand Sharma
                        address_of_authorised Signatory: 405, Pinnacle House, Kandiwali, Mumbai 400001
                        email_id: anand.sharma@abc.com
                        mobile_no: 9912332199
                        country: IND
                        subscriber_id: sit.grab.in
                        unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                        callback_url: /ondc/onboarding
                        key_pair: 
                          signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                          encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                          valid_from: 2022-07-08T13:44:54.101Z
                          valid_until: 2022-07-08T13:44:54.101Z
                      network_participant: 
                          [
                            {
                            subscriber_url: /buyerAppl,  
                            domain: nic2004:52110,
                            type: buyerApp,
                            msn: false,
                            city_code: ["std:080"]
                            },
                            {
                            subscriber_url: /sellerAppl,  
                            domain: nic2004:52110,
                            type: sellerApp,
                            msn: false,
                            city_code: ["std:080"]
                            }
                          ]
                          
                ops_no_5:
                  value:
                    context: 
                      operation:
                        ops_no: 5
                    message:
                      request_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                      timestamp: 2022-07-08T13:44:54.101Z
                      entity: 
                        gst: 
                          legal_entity_name: ABC Incorporates
                          business_address: Trade World, Mansarpur, Coorg, Karnataka 333333
                          city_code: [std:080]
                          gst_no: 07AAACN2082N4Z7
                        pan: 
                          name_as_per_pan: ABC Incorporates
                          pan_no: ASDFP7657Q
                          date_of_incorporation: 23/06/1982
                        name_of_authorised_signatory: Anand Sharma
                        address_of_authorised Signatory: 405, Pinnacle House, Kandiwali, Mumbai 400001
                        email_id: anand.sharma@abc.com
                        mobile_no: 9912332199
                        country: IND
                        subscriber_id: sit.grab.in
                        unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04
                        callback_url: /ondc/onboarding
                        key_pair: 
                          signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                          encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                          valid_from: 2022-07-08T13:44:54.101Z
                          valid_until: 2022-07-08T13:44:54.101Z
                      network_participant: [
                        {
                          subscriber_url: /buyerApp1,
                          domain: nic2004:52110,
                          type: buyerApp,
                          msn: false,
                          city_code: ["std:080"]
                        },
                        {
                          subscriber_url: /sellerApp1,  
                          domain: nic2004:52110,
                          type: sellerApp,
                          msn: true,
                          city_code: ["std:080"],
                          seller_on_record: [
                            { 
                            unique_key_id: 27baa06d-f90a-486c-85e5-cc621b787f04,
                            key_pair: {
                              signing_public_key: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=,
                              encryption_public_key: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=,
                              valid_from: 2022-07-08T13:44:54.101Z,
                              valid_until: 2022-07-08T13:44:54.101Z
                            },
                            city_code: ["std:080"]
                            }
                          ]
                      }]
                
      responses:
        '200':
          description: Acknowledgement of message received
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: object
                    properties:
                      ack:
                        $ref: '#/components/schemas/Ack'
                    required:
                      - ack
                  error:
                    $ref: '#/components/schemas/Error'
                required:
                  - message
  /subscriber_url/on_subscribe:
    post:
      tags:
        - ONDC Network Participant Onboarding
      description: to be hosted by subscriber
      requestBody:
        description: Onboard
        content:
          application/json:
            schema:
              type: object
              properties:
                subscriber_id:
                  type: string
                  description: A unique ID describing a subscriber on a network.
                  example: abc.com
                challenge:
                  type: string
                  description: String encrypted using the subscriber’s old encryption public key
                  example: encrypted_challenge_string
      responses:
        "200":
          description: Successful subscription
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer: 
                    type: string
                    description: Decrypted value
                    example: decrypted_challange_string
  /lookup:
      post:
        tags:
          - ONDC Network Participant Onboarding
        description: subscriber
        requestBody:
          description: Onboard
          content:
            application/json:
              schema:
                type: object
                properties:
                  sender_subscriber_id:  
                    type: string  
                    description: A unique ID describing a subscriber on a network.
                    example: "abc.com"
                  request_id:
                    type: string  
                    description: A unique ID describing request ID.
                    example: "4995c9a1-fc57-472d-9736-4e8a9ed1810f"
                  timestamp:
                    type: string
                    format: date-time
                    example: 2022-07-07T02:52:29.001Z
                  search_parameters:
                    type: object
                    properties:
                      country:
                        type: string
                        description: country
                        example: IND
                      domain:
                        type: string  
                        description: Industry domain of the subscriber
                        example: "nic2004:52110"
                      type:
                        type: string
                        description: buyerApp | sellerApp | gateway
                        example: "buyerApp"
                      city:
                        type: string
                        description: City code
                        example: "std:080"
                      subscriber_id:  
                        type: string  
                        description: A unique ID describing a subscriber on a network.
                        example: "abc.com"
                      
                      
                      
                  signature:
                    type: string
                    format: byte
                    description: >
                      Sign complete search_parameters json object using sign_private_key. <br> sign(country|domain|type|city|subscribeId) => sign(IND|nic2004:52110|sellerApp|std:083|fossgentechnologies.com) <br>
                      This will be verified using signature public key configured at ONDC registry
                    example: EoraSMAdJBJGxXjI/KgGhst4d6y1Vu2M6Z938/qAuJBV8hC9RUhNtwU+yL/pJeKGnxFgWxcW3FwlpTJCbSGdAA==
                required:
                    - request_id 
                    - sender_subscriber_id
                    - timestamp
                    - signature
                    - search_parameters
        responses:
          '200':
            description: Acknowledgement of message received
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    subscriber_id:
                      type: string  
                      description: A unique ID describing a subscriber on a network.
                      example: abc.com
                    unique_key_id:
                      type: string  
                      description: A unique ID describing key pair of a subscriber.
                      example: 27baa06d-f90a-486c-85e5-cc621b787f04  
                    country:
                      type: string  
                      description: Country code as per ISO 3166-1 and ISO 3166-2 format
                      example: "IND"
                    city_code:
                      type: array
                      items:
                        $ref: '#/components/schemas/City'
                    domain:
                      type: string  
                      description: Industry domain of the subscriber
                      example: "nic2004:52110"
                    type:
                      type: string
                      description: buyerApp | sellerApp | gateway
                      example: sellerApp
                    msn:
                      type: string
                      description: true | false
                      example: true
                    signing_public_key:
                      type: string  
                      format: byte 
                      description: Public key used by the subscriber to sign every request it makes
                      example: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
                    encr_public_key:
                      type: string  
                      format: byte
                      description: Encryption public key of the subscriber
                      example: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
                    valid_from:
                      type: string 
                      format: date-time  
                      description: Keys valid from
                      example: 2022-07-07T02:52:29.001Z
                    valid_until:
                      type: string 
                      format: date-time  
                      description: Keys valid until
                      example: 2022-07-07T02:52:29.001Z
                    created:  
                      type: string
                      format: date-time
                      description: Created timestamp
                      example: 2022-07-07T02:52:29.001Z
                    updated:
                      type: string
                      format: date-time
                      description: Updated timestamp
                      example: 2022-07-07T02:52:29.001Z
                    network_participant:
                      type: array
                      items:
                        $ref: '#/components/schemas/NetworkParticipant'
components:
  schemas:
    Ack:
      description: Describes the ACK response
      type: object
      properties:
        status:
          type: string
          description: 'Describe the status of the ACK response. If schema validation passes, status is ACK else it is NACK'
          enum:
            - ACK
            - NACK
      required:
        - status
    Error:
      description: Describes an error object
      type: object
      properties:
        type:
          type: string
          enum:
            - CONTEXT-ERROR
            - CORE-ERROR
            - DOMAIN-ERROR
            - POLICY-ERROR
            - JSON-SCHEMA-ERROR
        code:
          type: string
          description: 'ONDC specific error code. For full list of error codes, refer to docs/drafts/Error Codes.md of this repo'
        path:
          type: string
          description: Path to json schema generating the error. Used only during json schema validation errors
        message:
          type: string
          description: Human readable message describing the error
      required:
        - type
        - code
    Context:
      type: object
      properties:
        ops_no:
          type: integer
          format: int32
          enum: [1,2,3,4,5,6,7,8,9,10,11,12]
          example: 1
          description: 
            1 - Buyer New entity registration <br>
            2 - Non-MSN Seller New entity registration <br>
            3 - MSN Seller New entity registration <br>
            4 - Buyer and Non-MSN Seller new registration  <br>
            5 - Buyer and MSN Seller new registration <br>
            6 - Buyer/Non-MSN/MSN SellerApp key rotation <br>
            7 - MSN Seller changing keys for Seller on Record  <br>
            8 - Buyer adding New network participant for Non-MSN Seller <br>
            9 - Buyer adding New network participant for MSN Seller <br>
            10 - MSN Seller adding new seller on record <br>
            11 - BuyerApp/SellerApp amending city <br>
            12 - MSN Seller amending Seller on record city  <br>
              
           
    Entity:
      type: object
      properties:
        gst:
          type: object
          properties:
            legal_entity_name:
              type: string
              example: ABC Incorporates
            business_address:
              type: string
              example: Trade World, Mansarpur, Coorg, Karnataka 333333
            city_code:
              type: array
              items:
                $ref: '#/components/schemas/City'
            gst_no:
              type: string
              example: "07AAACN2082N4Z7"
        pan:
          type: object
          properties:
              name_as_per_pan:
                type: string
                description: This shall be used to match the name as per PAN with Income Tax Department
                example: "ABC Incorporates"
              pan_no:
                type: string
                description: Permanent Account Number issued by Income Tax Department. First five alphabets followed by four numeric followed by one alphabet
                example: "ASDFP7657Q"
              date_of_incorporation:
                type: string
                format: date
                description: DD/MM/YYYY format
                example: "23/06/1982"
        name_of_authorised_signatory:
          type: string
          example: Anand Sharma
        address_of_authorised Signatory:
          type: string
          example: 405, Pinnacle House, Kandiwali, Mumbai 400001
        email_id:
          type: string
          example: anand.sharma@abc.com
        mobile_no:
          type: string
          example: 9912332199
        country:  
          type: string  
          description: Country code as per ISO 3166-1 and ISO 3166-2 format
          example: "IND"
        subscriber_id:
          type: string
          example: sit.grab.in
        unique_key_id:
          description: A unique number for tracking NP's key pairs.
          example: "nova-some-uuid"
          type: string
        callback_url:
          type: string
          description: it should be relative to subscriber_id mentioned domain. In below example with subscriber _id as abc.com, regsitry will call https://abc.com/ondc/onboarding/on_subscribe
          example: "/ondc/onboarding"
        key_pair:
          $ref: '#/components/schemas/KeyPair'
          
    NetworkParticipant:
      type: "object"
      properties:
        subscriber_url:
          type: string
          example: /bapl
        domain:
          type: string
          description: Industry domain of the subscriber
          example: "nic2004:52110"  
        type:
          type: string
          enum:
          - buyerApp
          - sellerApp
          - gateway
        msn:
          type: string
        city_code:
          type: array
          items:
            $ref: '#/components/schemas/City'
        seller_on_record:
          type: array
          items:
            $ref: '#/components/schemas/SellerOnRecord'
        
    SellerOnRecord:
      type: "object"
      properties:
        unique_key_id:
          type: string
        key_pair:
          $ref: '#/components/schemas/KeyPair'
        city_code:
          type: array
          items:
            $ref: '#/components/schemas/City'
    City:
      description: Codification of city code will be using the std code of the city e.g. for Bengaluru, city code is 'std:080'        
      type: string
      example: "std:080"

    KeyPair:
      type: object
      properties:
        signing_public_key:
          type: string
          format: byte
          example: QSax2KT4UiTUWUqoVUaEcWhBcGTTNu+Sf8EMDRY1GaE=
        encryption_public_key:
          type: string
          format: byte #base64 encoded characters
          example: O74ukMymk4KZnVs3sZhU2U7RXpaZ/qiOUMk5NWt6rbI=
        valid_from:
          type: string
          format: date-time
          description: use IST time zone
          example: 2022-07-07T02:52:29.001Z
        valid_until:
          type: string
          format: date-time
          description: use IST time zone
          example: 2022-07-07T02:52:29.001Z